"""Inference bounds for the verification history in the synthetic demo."""
import math

from app.core.config import settings


MAX_PRIOR_VERIFICATIONS = 12
# Beta(1, 5) smoothing at the longest history generated by the simulator.
HISTORY_RATE_BOUNDS = (1 / (MAX_PRIOR_VERIFICATIONS + 6),
                       (MAX_PRIOR_VERIFICATIONS + 1) / (MAX_PRIOR_VERIFICATIONS + 6))


def bounded_history(features: dict) -> dict:
    """Copy model inputs, keeping original evidence and non-history fields intact.

    Clipping to nominal support limits extrapolation; it does not establish
    calibration or joint support. Sparse histories retain the population prior.
    """
    count = float(features.get("prior_verifications", 0))
    rate = float(features.get("prior_verify_abandonment_rate", 1 / 6))
    if not math.isfinite(count) or count < 0 or not math.isfinite(rate) or not 0 <= rate <= 1:
        raise ValueError("History requires a finite nonnegative count and a rate between 0 and 1")
    low, high = HISTORY_RATE_BOUNDS
    return {
        **features,
        "prior_verifications": min(count, MAX_PRIOR_VERIFICATIONS),
        "prior_verify_abandonment_rate": (
            1 / 6 if count < settings.min_personalization_history else max(low, min(rate, high))
        ),
    }
